export const APP_WRITE_ID = '660be278754539c84609'
export const DB_ID = 'data-base-crm-system'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
